language: php

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

before_install:
    - composer self-update

install:
    - composer install
    - npm install -g grunt-cli
    - npm install

script: grunt test
